kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc-persmt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
