kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc-persmt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
